apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

vars:
- name: MOSQUITTO_SERVICE
  objref:
    kind: Service
    name: mosquitto
    apiVersion: v1
