apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  ports:
  - protocol: TCP
    port: 1883
  selector:
    app: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7777
  selector:
    app: server
